# Generated by Django 4.2.13 on 2026-03-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('default', 'Default'), ('low', 'LOW')], default='default', max_length=10),
        ),
    ]
