# Generated by Django 4.2.13 on 2026-03-22 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadLetterJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_reason', models.TextField()),
                ('failed_at', models.DateTimeField(auto_now_add=True)),
                ('retry_count', models.PositiveSmallIntegerField()),
                ('last_error', models.TextField()),
                ('replayed', models.BooleanField(default=False)),
                ('replayed_at', models.DateTimeField(blank=True, null=True)),
                ('original_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deal_letter', to='jobs.job')),
            ],
            options={
                'ordering': ['-failed_at'],
            },
        ),
    ]
