apiVersion: batch/v1
kind: Job
metadata:
  name: jobqueue-migrate
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migrate
        image: <ACCOUNT_ID>.dkr.ecr.eu-north-1.amazonaws.com/jobqueue:v1
        command: ["python", "manage.py", "migrate"]
        envFrom:
        - configMapRef:
            name: jobqueue-config
        - secretRef:
            name: jobqueue-secret
